/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xlang_java_Xlang */

#ifndef _Included_xlang_java_Xlang
#define _Included_xlang_java_Xlang
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
